<?php

session_start();

date_default_timezone_set('america/sao_paulo');
header('Content-Type: text/html; charset=utf-8');
mysql_query("SET NAMES 'utf8'");
mysql_query('SET character_set_connection=utf8');
mysql_query('SET character_set_client=utf8');
mysql_query('SET character_set_results=utf8');

include "../conexao.php";

$dia = $_POST['dia'];
$disciplina = $_POST['disciplina'];
$dupla = $_POST['dupla'];
$professor = $_POST['professor'];
$cpf = $_POST['cpfOficial'];

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 18, '".$_POST['sangrVD18']."', '".$_POST['sangrVTM18']."', '".$_POST['sangrVM18']."', '".$_POST['pmgVD18']."', '".$_POST['pmgVTM18']."', '".$_POST['pmgVM18']."', '".$_POST['psvVD18']."', '".$_POST['psvVTM18']."', '".$_POST['psvVM18']."', '".($_POST['pmgVD18']+$_POST['psvVD18'])."', '".($_POST['pmgVTM18']+$_POST['psvVTM18'])."', '".($_POST['pmgVM18']+$_POST['psvVM18'])."', '".$_POST['sangrPD18']."', '".$_POST['sangrPTM18']."', '".$_POST['sangrPM18']."', '".$_POST['pmgPD18']."', '".$_POST['pmgPTM18']."', '".$_POST['pmgPM18']."', '".$_POST['psvPD18']."', '".$_POST['psvPTM18']."', '".$_POST['psvPM18']."', '".($_POST['pmgPD18']+$_POST['psvPD18'])."', '".($_POST['pmgPTM18']+$_POST['psvPTM18'])."', '".($_POST['pmgPM18']+$_POST['psvPM18'])."', '".$_POST['mobilidade18']."', '".$_POST['furca18']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 17, '".$_POST['sangrVD17']."', '".$_POST['sangrVTM17']."', '".$_POST['sangrVM17']."', '".$_POST['pmgVD17']."', '".$_POST['pmgVTM17']."', '".$_POST['pmgVM17']."', '".$_POST['psvVD17']."', '".$_POST['psvVTM17']."', '".$_POST['psvVM17']."', '".($_POST['pmgVD17']+$_POST['psvVD17'])."', '".($_POST['pmgVTM17']+$_POST['psvVTM17'])."', '".($_POST['pmgVM17']+$_POST['psvVM17'])."', '".$_POST['sangrPD17']."', '".$_POST['sangrPTM17']."', '".$_POST['sangrPM17']."', '".$_POST['pmgPD17']."', '".$_POST['pmgPTM17']."', '".$_POST['pmgPM17']."', '".$_POST['psvPD17']."', '".$_POST['psvPTM17']."', '".$_POST['psvPM17']."', '".($_POST['pmgPD17']+$_POST['psvPD17'])."', '".($_POST['pmgPTM17']+$_POST['psvPTM17'])."', '".($_POST['pmgPM17']+$_POST['psvPM17'])."', '".$_POST['mobilidade17']."', '".$_POST['furca17']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 16, '".$_POST['sangrVD16']."', '".$_POST['sangrVTM16']."', '".$_POST['sangrVM16']."', '".$_POST['pmgVD16']."', '".$_POST['pmgVTM16']."', '".$_POST['pmgVM16']."', '".$_POST['psvVD16']."', '".$_POST['psvVTM16']."', '".$_POST['psvVM16']."', '".($_POST['pmgVD16']+$_POST['psvVD16'])."', '".($_POST['pmgVTM16']+$_POST['psvVTM16'])."', '".($_POST['pmgVM16']+$_POST['psvVM16'])."', '".$_POST['sangrPD16']."', '".$_POST['sangrPTM16']."', '".$_POST['sangrPM16']."', '".$_POST['pmgPD16']."', '".$_POST['pmgPTM16']."', '".$_POST['pmgPM16']."', '".$_POST['psvPD16']."', '".$_POST['psvPTM16']."', '".$_POST['psvPM16']."', '".($_POST['pmgPD16']+$_POST['psvPD16'])."', '".($_POST['pmgPTM16']+$_POST['psvPTM16'])."', '".($_POST['pmgPM16']+$_POST['psvPM16'])."', '".$_POST['mobilidade16']."', '".$_POST['furca16']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 15, '".$_POST['sangrVD15']."', '".$_POST['sangrVTM15']."', '".$_POST['sangrVM15']."', '".$_POST['pmgVD15']."', '".$_POST['pmgVTM15']."', '".$_POST['pmgVM15']."', '".$_POST['psvVD15']."', '".$_POST['psvVTM15']."', '".$_POST['psvVM15']."', '".($_POST['pmgVD15']+$_POST['psvVD15'])."', '".($_POST['pmgVTM15']+$_POST['psvVTM15'])."', '".($_POST['pmgVM15']+$_POST['psvVM15'])."', '".$_POST['sangrPD15']."', '".$_POST['sangrPTM15']."', '".$_POST['sangrPM15']."', '".$_POST['pmgPD15']."', '".$_POST['pmgPTM15']."', '".$_POST['pmgPM15']."', '".$_POST['psvPD15']."', '".$_POST['psvPTM15']."', '".$_POST['psvPM15']."', '".($_POST['pmgPD15']+$_POST['psvPD15'])."', '".($_POST['pmgPTM15']+$_POST['psvPTM15'])."', '".($_POST['pmgPM15']+$_POST['psvPM15'])."', '".$_POST['mobilidade15']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 14, '".$_POST['sangrVD14']."', '".$_POST['sangrVTM14']."', '".$_POST['sangrVM14']."', '".$_POST['pmgVD14']."', '".$_POST['pmgVTM14']."', '".$_POST['pmgVM14']."', '".$_POST['psvVD14']."', '".$_POST['psvVTM14']."', '".$_POST['psvVM14']."', '".($_POST['pmgVD14']+$_POST['psvVD14'])."', '".($_POST['pmgVTM14']+$_POST['psvVTM14'])."', '".($_POST['pmgVM14']+$_POST['psvVM14'])."', '".$_POST['sangrPD14']."', '".$_POST['sangrPTM14']."', '".$_POST['sangrPM14']."', '".$_POST['pmgPD14']."', '".$_POST['pmgPTM14']."', '".$_POST['pmgPM14']."', '".$_POST['psvPD14']."', '".$_POST['psvPTM14']."', '".$_POST['psvPM14']."', '".($_POST['pmgPD14']+$_POST['psvPD14'])."', '".($_POST['pmgPTM14']+$_POST['psvPTM14'])."', '".($_POST['pmgPM14']+$_POST['psvPM14'])."', '".$_POST['mobilidade14']."', '".$_POST['furca14D']."', '".$_POST['furca14M']."', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 13, '".$_POST['sangrVD13']."', '".$_POST['sangrVTM13']."', '".$_POST['sangrVM13']."', '".$_POST['pmgVD13']."', '".$_POST['pmgVTM13']."', '".$_POST['pmgVM13']."', '".$_POST['psvVD13']."', '".$_POST['psvVTM13']."', '".$_POST['psvVM13']."', '".($_POST['pmgVD13']+$_POST['psvVD13'])."', '".($_POST['pmgVTM13']+$_POST['psvVTM13'])."', '".($_POST['pmgVM13']+$_POST['psvVM13'])."', '".$_POST['sangrPD13']."', '".$_POST['sangrPTM13']."', '".$_POST['sangrPM13']."', '".$_POST['pmgPD13']."', '".$_POST['pmgPTM13']."', '".$_POST['pmgPM13']."', '".$_POST['psvPD13']."', '".$_POST['psvPTM13']."', '".$_POST['psvPM13']."', '".($_POST['pmgPD13']+$_POST['psvPD13'])."', '".($_POST['pmgPTM13']+$_POST['psvPTM13'])."', '".($_POST['pmgPM13']+$_POST['psvPM13'])."', '".$_POST['mobilidade13']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 12, '".$_POST['sangrVD12']."', '".$_POST['sangrVTM12']."', '".$_POST['sangrVM12']."', '".$_POST['pmgVD12']."', '".$_POST['pmgVTM12']."', '".$_POST['pmgVM12']."', '".$_POST['psvVD12']."', '".$_POST['psvVTM12']."', '".$_POST['psvVM12']."', '".($_POST['pmgVD12']+$_POST['psvVD12'])."', '".($_POST['pmgVTM12']+$_POST['psvVTM12'])."', '".($_POST['pmgVM12']+$_POST['psvVM12'])."', '".$_POST['sangrPD12']."', '".$_POST['sangrPTM12']."', '".$_POST['sangrPM12']."', '".$_POST['pmgPD12']."', '".$_POST['pmgPTM12']."', '".$_POST['pmgPM12']."', '".$_POST['psvPD12']."', '".$_POST['psvPTM12']."', '".$_POST['psvPM12']."', '".($_POST['pmgPD12']+$_POST['psvPD12'])."', '".($_POST['pmgPTM12']+$_POST['psvPTM12'])."', '".($_POST['pmgPM12']+$_POST['psvPM12'])."', '".$_POST['mobilidade12']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 11, '".$_POST['sangrVD11']."', '".$_POST['sangrVTM11']."', '".$_POST['sangrVM11']."', '".$_POST['pmgVD11']."', '".$_POST['pmgVTM11']."', '".$_POST['pmgVM11']."', '".$_POST['psvVD11']."', '".$_POST['psvVTM11']."', '".$_POST['psvVM11']."', '".($_POST['pmgVD11']+$_POST['psvVD11'])."', '".($_POST['pmgVTM11']+$_POST['psvVTM11'])."', '".($_POST['pmgVM11']+$_POST['psvVM11'])."', '".$_POST['sangrPD11']."', '".$_POST['sangrPTM11']."', '".$_POST['sangrPM11']."', '".$_POST['pmgPD11']."', '".$_POST['pmgPTM11']."', '".$_POST['pmgPM11']."', '".$_POST['psvPD11']."', '".$_POST['psvPTM11']."', '".$_POST['psvPM11']."', '".($_POST['pmgPD11']+$_POST['psvPD11'])."', '".($_POST['pmgPTM11']+$_POST['psvPTM11'])."', '".($_POST['pmgPM11']+$_POST['psvPM11'])."', '".$_POST['mobilidade11']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 21, '".$_POST['sangrVD21']."', '".$_POST['sangrVTM21']."', '".$_POST['sangrVM21']."', '".$_POST['pmgVD21']."', '".$_POST['pmgVTM21']."', '".$_POST['pmgVM21']."', '".$_POST['psvVD21']."', '".$_POST['psvVTM21']."', '".$_POST['psvVM21']."', '".($_POST['pmgVD21']+$_POST['psvVD21'])."', '".($_POST['pmgVTM21']+$_POST['psvVTM21'])."', '".($_POST['pmgVM21']+$_POST['psvVM21'])."', '".$_POST['sangrPD21']."', '".$_POST['sangrPTM21']."', '".$_POST['sangrPM21']."', '".$_POST['pmgPD21']."', '".$_POST['pmgPTM21']."', '".$_POST['pmgPM21']."', '".$_POST['psvPD21']."', '".$_POST['psvPTM21']."', '".$_POST['psvPM21']."', '".($_POST['pmgPD21']+$_POST['psvPD21'])."', '".($_POST['pmgPTM21']+$_POST['psvPTM21'])."', '".($_POST['pmgPM21']+$_POST['psvPM21'])."', '".$_POST['mobilidade21']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 22, '".$_POST['sangrVD22']."', '".$_POST['sangrVTM22']."', '".$_POST['sangrVM22']."', '".$_POST['pmgVD22']."', '".$_POST['pmgVTM22']."', '".$_POST['pmgVM22']."', '".$_POST['psvVD22']."', '".$_POST['psvVTM22']."', '".$_POST['psvVM22']."', '".($_POST['pmgVD22']+$_POST['psvVD22'])."', '".($_POST['pmgVTM22']+$_POST['psvVTM22'])."', '".($_POST['pmgVM22']+$_POST['psvVM22'])."', '".$_POST['sangrPD22']."', '".$_POST['sangrPTM22']."', '".$_POST['sangrPM22']."', '".$_POST['pmgPD22']."', '".$_POST['pmgPTM22']."', '".$_POST['pmgPM22']."', '".$_POST['psvPD22']."', '".$_POST['psvPTM22']."', '".$_POST['psvPM22']."', '".($_POST['pmgPD22']+$_POST['psvPD22'])."', '".($_POST['pmgPTM22']+$_POST['psvPTM22'])."', '".($_POST['pmgPM22']+$_POST['psvPM22'])."', '".$_POST['mobilidade22']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 23, '".$_POST['sangrVD23']."', '".$_POST['sangrVTM23']."', '".$_POST['sangrVM23']."', '".$_POST['pmgVD23']."', '".$_POST['pmgVTM23']."', '".$_POST['pmgVM23']."', '".$_POST['psvVD23']."', '".$_POST['psvVTM23']."', '".$_POST['psvVM23']."', '".($_POST['pmgVD23']+$_POST['psvVD23'])."', '".($_POST['pmgVTM23']+$_POST['psvVTM23'])."', '".($_POST['pmgVM23']+$_POST['psvVM23'])."', '".$_POST['sangrPD23']."', '".$_POST['sangrPTM23']."', '".$_POST['sangrPM23']."', '".$_POST['pmgPD23']."', '".$_POST['pmgPTM23']."', '".$_POST['pmgPM23']."', '".$_POST['psvPD23']."', '".$_POST['psvPTM23']."', '".$_POST['psvPM23']."', '".($_POST['pmgPD23']+$_POST['psvPD23'])."', '".($_POST['pmgPTM23']+$_POST['psvPTM23'])."', '".($_POST['pmgPM23']+$_POST['psvPM23'])."', '".$_POST['mobilidade23']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 24, '".$_POST['sangrVD24']."', '".$_POST['sangrVTM24']."', '".$_POST['sangrVM24']."', '".$_POST['pmgVD24']."', '".$_POST['pmgVTM24']."', '".$_POST['pmgVM24']."', '".$_POST['psvVD24']."', '".$_POST['psvVTM24']."', '".$_POST['psvVM24']."', '".($_POST['pmgVD24']+$_POST['psvVD24'])."', '".($_POST['pmgVTM24']+$_POST['psvVTM24'])."', '".($_POST['pmgVM24']+$_POST['psvVM24'])."', '".$_POST['sangrPD24']."', '".$_POST['sangrPTM24']."', '".$_POST['sangrPM24']."', '".$_POST['pmgPD24']."', '".$_POST['pmgPTM24']."', '".$_POST['pmgPM24']."', '".$_POST['psvPD24']."', '".$_POST['psvPTM24']."', '".$_POST['psvPM24']."', '".($_POST['pmgPD24']+$_POST['psvPD24'])."', '".($_POST['pmgPTM24']+$_POST['psvPTM24'])."', '".($_POST['pmgPM24']+$_POST['psvPM24'])."', '".$_POST['mobilidade24']."', '".$_POST['furca24D']."', '".$_POST['furca24M']."', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 25, '".$_POST['sangrVD25']."', '".$_POST['sangrVTM25']."', '".$_POST['sangrVM25']."', '".$_POST['pmgVD25']."', '".$_POST['pmgVTM25']."', '".$_POST['pmgVM25']."', '".$_POST['psvVD25']."', '".$_POST['psvVTM25']."', '".$_POST['psvVM25']."', '".($_POST['pmgVD25']+$_POST['psvVD25'])."', '".($_POST['pmgVTM25']+$_POST['psvVTM25'])."', '".($_POST['pmgVM25']+$_POST['psvVM25'])."', '".$_POST['sangrPD25']."', '".$_POST['sangrPTM25']."', '".$_POST['sangrPM25']."', '".$_POST['pmgPD25']."', '".$_POST['pmgPTM25']."', '".$_POST['pmgPM25']."', '".$_POST['psvPD25']."', '".$_POST['psvPTM25']."', '".$_POST['psvPM25']."', '".($_POST['pmgPD25']+$_POST['psvPD25'])."', '".($_POST['pmgPTM25']+$_POST['psvPTM25'])."', '".($_POST['pmgPM25']+$_POST['psvPM25'])."', '".$_POST['mobilidade25']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 26, '".$_POST['sangrVD26']."', '".$_POST['sangrVTM26']."', '".$_POST['sangrVM26']."', '".$_POST['pmgVD26']."', '".$_POST['pmgVTM26']."', '".$_POST['pmgVM26']."', '".$_POST['psvVD26']."', '".$_POST['psvVTM26']."', '".$_POST['psvVM26']."', '".($_POST['pmgVD26']+$_POST['psvVD26'])."', '".($_POST['pmgVTM26']+$_POST['psvVTM26'])."', '".($_POST['pmgVM26']+$_POST['psvVM26'])."', '".$_POST['sangrPD26']."', '".$_POST['sangrPTM26']."', '".$_POST['sangrPM26']."', '".$_POST['pmgPD26']."', '".$_POST['pmgPTM26']."', '".$_POST['pmgPM26']."', '".$_POST['psvPD26']."', '".$_POST['psvPTM26']."', '".$_POST['psvPM26']."', '".($_POST['pmgPD26']+$_POST['psvPD26'])."', '".($_POST['pmgPTM26']+$_POST['psvPTM26'])."', '".($_POST['pmgPM26']+$_POST['psvPM26'])."', '".$_POST['mobilidade26']."', '".$_POST['furca26']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 27, '".$_POST['sangrVD27']."', '".$_POST['sangrVTM27']."', '".$_POST['sangrVM27']."', '".$_POST['pmgVD27']."', '".$_POST['pmgVTM27']."', '".$_POST['pmgVM27']."', '".$_POST['psvVD27']."', '".$_POST['psvVTM27']."', '".$_POST['psvVM27']."', '".($_POST['pmgVD27']+$_POST['psvVD27'])."', '".($_POST['pmgVTM27']+$_POST['psvVTM27'])."', '".($_POST['pmgVM27']+$_POST['psvVM27'])."', '".$_POST['sangrPD27']."', '".$_POST['sangrPTM27']."', '".$_POST['sangrPM27']."', '".$_POST['pmgPD27']."', '".$_POST['pmgPTM27']."', '".$_POST['pmgPM27']."', '".$_POST['psvPD27']."', '".$_POST['psvPTM27']."', '".$_POST['psvPM27']."', '".($_POST['pmgPD27']+$_POST['psvPD27'])."', '".($_POST['pmgPTM27']+$_POST['psvPTM27'])."', '".($_POST['pmgPM27']+$_POST['psvPM27'])."', '".$_POST['mobilidade27']."', '".$_POST['furca27']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 28, '".$_POST['sangrVD28']."', '".$_POST['sangrVTM28']."', '".$_POST['sangrVM28']."', '".$_POST['pmgVD28']."', '".$_POST['pmgVTM28']."', '".$_POST['pmgVM28']."', '".$_POST['psvVD28']."', '".$_POST['psvVTM28']."', '".$_POST['psvVM28']."', '".($_POST['pmgVD28']+$_POST['psvVD28'])."', '".($_POST['pmgVTM28']+$_POST['psvVTM28'])."', '".($_POST['pmgVM28']+$_POST['psvVM28'])."', '".$_POST['sangrPD28']."', '".$_POST['sangrPTM28']."', '".$_POST['sangrPM28']."', '".$_POST['pmgPD28']."', '".$_POST['pmgPTM28']."', '".$_POST['pmgPM28']."', '".$_POST['psvPD28']."', '".$_POST['psvPTM28']."', '".$_POST['psvPM28']."', '".($_POST['pmgPD28']+$_POST['psvPD28'])."', '".($_POST['pmgPTM28']+$_POST['psvPTM28'])."', '".($_POST['pmgPM28']+$_POST['psvPM28'])."', '".$_POST['mobilidade28']."', '".$_POST['furca28']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

// inferior

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 48, '".$_POST['sangrVD48']."', '".$_POST['sangrVTM48']."', '".$_POST['sangrVM48']."', '".$_POST['pmgVD48']."', '".$_POST['pmgVTM48']."', '".$_POST['pmgVM48']."', '".$_POST['psvVD48']."', '".$_POST['psvVTM48']."', '".$_POST['psvVM48']."', '".($_POST['pmgVD48']+$_POST['psvVD48'])."', '".($_POST['pmgVTM48']+$_POST['psvVTM48'])."', '".($_POST['pmgVM48']+$_POST['psvVM48'])."', '".$_POST['sangrPD48']."', '".$_POST['sangrPTM48']."', '".$_POST['sangrPM48']."', '".$_POST['pmgPD48']."', '".$_POST['pmgPTM48']."', '".$_POST['pmgPM48']."', '".$_POST['psvPD48']."', '".$_POST['psvPTM48']."', '".$_POST['psvPM48']."', '".($_POST['pmgPD48']+$_POST['psvPD48'])."', '".($_POST['pmgPTM48']+$_POST['psvPTM48'])."', '".($_POST['pmgPM48']+$_POST['psvPM48'])."', '".$_POST['mobilidade48']."', '".$_POST['furca48']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 47, '".$_POST['sangrVD47']."', '".$_POST['sangrVTM47']."', '".$_POST['sangrVM47']."', '".$_POST['pmgVD47']."', '".$_POST['pmgVTM47']."', '".$_POST['pmgVM47']."', '".$_POST['psvVD47']."', '".$_POST['psvVTM47']."', '".$_POST['psvVM47']."', '".($_POST['pmgVD47']+$_POST['psvVD47'])."', '".($_POST['pmgVTM47']+$_POST['psvVTM47'])."', '".($_POST['pmgVM47']+$_POST['psvVM47'])."', '".$_POST['sangrPD47']."', '".$_POST['sangrPTM47']."', '".$_POST['sangrPM47']."', '".$_POST['pmgPD47']."', '".$_POST['pmgPTM47']."', '".$_POST['pmgPM47']."', '".$_POST['psvPD47']."', '".$_POST['psvPTM47']."', '".$_POST['psvPM47']."', '".($_POST['pmgPD47']+$_POST['psvPD47'])."', '".($_POST['pmgPTM47']+$_POST['psvPTM47'])."', '".($_POST['pmgPM47']+$_POST['psvPM47'])."', '".$_POST['mobilidade47']."', '".$_POST['furca47']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 46, '".$_POST['sangrVD46']."', '".$_POST['sangrVTM46']."', '".$_POST['sangrVM46']."', '".$_POST['pmgVD46']."', '".$_POST['pmgVTM46']."', '".$_POST['pmgVM46']."', '".$_POST['psvVD46']."', '".$_POST['psvVTM46']."', '".$_POST['psvVM46']."', '".($_POST['pmgVD46']+$_POST['psvVD46'])."', '".($_POST['pmgVTM46']+$_POST['psvVTM46'])."', '".($_POST['pmgVM46']+$_POST['psvVM46'])."', '".$_POST['sangrPD46']."', '".$_POST['sangrPTM46']."', '".$_POST['sangrPM46']."', '".$_POST['pmgPD46']."', '".$_POST['pmgPTM46']."', '".$_POST['pmgPM46']."', '".$_POST['psvPD46']."', '".$_POST['psvPTM46']."', '".$_POST['psvPM46']."', '".($_POST['pmgPD46']+$_POST['psvPD46'])."', '".($_POST['pmgPTM46']+$_POST['psvPTM46'])."', '".($_POST['pmgPM46']+$_POST['psvPM46'])."', '".$_POST['mobilidade46']."', '".$_POST['furca46']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 45, '".$_POST['sangrVD45']."', '".$_POST['sangrVTM45']."', '".$_POST['sangrVM45']."', '".$_POST['pmgVD45']."', '".$_POST['pmgVTM45']."', '".$_POST['pmgVM45']."', '".$_POST['psvVD45']."', '".$_POST['psvVTM45']."', '".$_POST['psvVM45']."', '".($_POST['pmgVD45']+$_POST['psvVD45'])."', '".($_POST['pmgVTM45']+$_POST['psvVTM45'])."', '".($_POST['pmgVM45']+$_POST['psvVM45'])."', '".$_POST['sangrPD45']."', '".$_POST['sangrPTM45']."', '".$_POST['sangrPM45']."', '".$_POST['pmgPD45']."', '".$_POST['pmgPTM45']."', '".$_POST['pmgPM45']."', '".$_POST['psvPD45']."', '".$_POST['psvPTM45']."', '".$_POST['psvPM45']."', '".($_POST['pmgPD45']+$_POST['psvPD45'])."', '".($_POST['pmgPTM45']+$_POST['psvPTM45'])."', '".($_POST['pmgPM45']+$_POST['psvPM45'])."', '".$_POST['mobilidade45']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 44, '".$_POST['sangrVD44']."', '".$_POST['sangrVTM44']."', '".$_POST['sangrVM44']."', '".$_POST['pmgVD44']."', '".$_POST['pmgVTM44']."', '".$_POST['pmgVM44']."', '".$_POST['psvVD44']."', '".$_POST['psvVTM44']."', '".$_POST['psvVM44']."', '".($_POST['pmgVD44']+$_POST['psvVD44'])."', '".($_POST['pmgVTM44']+$_POST['psvVTM44'])."', '".($_POST['pmgVM44']+$_POST['psvVM44'])."', '".$_POST['sangrPD44']."', '".$_POST['sangrPTM44']."', '".$_POST['sangrPM44']."', '".$_POST['pmgPD44']."', '".$_POST['pmgPTM44']."', '".$_POST['pmgPM44']."', '".$_POST['psvPD44']."', '".$_POST['psvPTM44']."', '".$_POST['psvPM44']."', '".($_POST['pmgPD44']+$_POST['psvPD44'])."', '".($_POST['pmgPTM44']+$_POST['psvPTM44'])."', '".($_POST['pmgPM44']+$_POST['psvPM44'])."', '".$_POST['mobilidade44']."', '".$_POST['furca44D']."', '".$_POST['furca44M']."', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 43, '".$_POST['sangrVD43']."', '".$_POST['sangrVTM43']."', '".$_POST['sangrVM43']."', '".$_POST['pmgVD43']."', '".$_POST['pmgVTM43']."', '".$_POST['pmgVM43']."', '".$_POST['psvVD43']."', '".$_POST['psvVTM43']."', '".$_POST['psvVM43']."', '".($_POST['pmgVD43']+$_POST['psvVD43'])."', '".($_POST['pmgVTM43']+$_POST['psvVTM43'])."', '".($_POST['pmgVM43']+$_POST['psvVM43'])."', '".$_POST['sangrPD43']."', '".$_POST['sangrPTM43']."', '".$_POST['sangrPM43']."', '".$_POST['pmgPD43']."', '".$_POST['pmgPTM43']."', '".$_POST['pmgPM43']."', '".$_POST['psvPD43']."', '".$_POST['psvPTM43']."', '".$_POST['psvPM43']."', '".($_POST['pmgPD43']+$_POST['psvPD43'])."', '".($_POST['pmgPTM43']+$_POST['psvPTM43'])."', '".($_POST['pmgPM43']+$_POST['psvPM43'])."', '".$_POST['mobilidade43']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 42, '".$_POST['sangrVD42']."', '".$_POST['sangrVTM42']."', '".$_POST['sangrVM42']."', '".$_POST['pmgVD42']."', '".$_POST['pmgVTM42']."', '".$_POST['pmgVM42']."', '".$_POST['psvVD42']."', '".$_POST['psvVTM42']."', '".$_POST['psvVM42']."', '".($_POST['pmgVD42']+$_POST['psvVD42'])."', '".($_POST['pmgVTM42']+$_POST['psvVTM42'])."', '".($_POST['pmgVM42']+$_POST['psvVM42'])."', '".$_POST['sangrPD42']."', '".$_POST['sangrPTM42']."', '".$_POST['sangrPM42']."', '".$_POST['pmgPD42']."', '".$_POST['pmgPTM42']."', '".$_POST['pmgPM42']."', '".$_POST['psvPD42']."', '".$_POST['psvPTM42']."', '".$_POST['psvPM42']."', '".($_POST['pmgPD42']+$_POST['psvPD42'])."', '".($_POST['pmgPTM42']+$_POST['psvPTM42'])."', '".($_POST['pmgPM42']+$_POST['psvPM42'])."', '".$_POST['mobilidade42']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 41, '".$_POST['sangrVD41']."', '".$_POST['sangrVTM41']."', '".$_POST['sangrVM41']."', '".$_POST['pmgVD41']."', '".$_POST['pmgVTM41']."', '".$_POST['pmgVM41']."', '".$_POST['psvVD41']."', '".$_POST['psvVTM41']."', '".$_POST['psvVM41']."', '".($_POST['pmgVD41']+$_POST['psvVD41'])."', '".($_POST['pmgVTM41']+$_POST['psvVTM41'])."', '".($_POST['pmgVM41']+$_POST['psvVM41'])."', '".$_POST['sangrPD41']."', '".$_POST['sangrPTM41']."', '".$_POST['sangrPM41']."', '".$_POST['pmgPD41']."', '".$_POST['pmgPTM41']."', '".$_POST['pmgPM41']."', '".$_POST['psvPD41']."', '".$_POST['psvPTM41']."', '".$_POST['psvPM41']."', '".($_POST['pmgPD41']+$_POST['psvPD41'])."', '".($_POST['pmgPTM41']+$_POST['psvPTM41'])."', '".($_POST['pmgPM41']+$_POST['psvPM41'])."', '".$_POST['mobilidade41']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 31, '".$_POST['sangrVD31']."', '".$_POST['sangrVTM31']."', '".$_POST['sangrVM31']."', '".$_POST['pmgVD31']."', '".$_POST['pmgVTM31']."', '".$_POST['pmgVM31']."', '".$_POST['psvVD31']."', '".$_POST['psvVTM31']."', '".$_POST['psvVM31']."', '".($_POST['pmgVD31']+$_POST['psvVD31'])."', '".($_POST['pmgVTM31']+$_POST['psvVTM31'])."', '".($_POST['pmgVM31']+$_POST['psvVM31'])."', '".$_POST['sangrPD31']."', '".$_POST['sangrPTM31']."', '".$_POST['sangrPM31']."', '".$_POST['pmgPD31']."', '".$_POST['pmgPTM31']."', '".$_POST['pmgPM31']."', '".$_POST['psvPD31']."', '".$_POST['psvPTM31']."', '".$_POST['psvPM31']."', '".($_POST['pmgPD31']+$_POST['psvPD31'])."', '".($_POST['pmgPTM31']+$_POST['psvPTM31'])."', '".($_POST['pmgPM31']+$_POST['psvPM31'])."', '".$_POST['mobilidade31']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 32, '".$_POST['sangrVD32']."', '".$_POST['sangrVTM32']."', '".$_POST['sangrVM32']."', '".$_POST['pmgVD32']."', '".$_POST['pmgVTM32']."', '".$_POST['pmgVM32']."', '".$_POST['psvVD32']."', '".$_POST['psvVTM32']."', '".$_POST['psvVM32']."', '".($_POST['pmgVD32']+$_POST['psvVD32'])."', '".($_POST['pmgVTM32']+$_POST['psvVTM32'])."', '".($_POST['pmgVM32']+$_POST['psvVM32'])."', '".$_POST['sangrPD32']."', '".$_POST['sangrPTM32']."', '".$_POST['sangrPM32']."', '".$_POST['pmgPD32']."', '".$_POST['pmgPTM32']."', '".$_POST['pmgPM32']."', '".$_POST['psvPD32']."', '".$_POST['psvPTM32']."', '".$_POST['psvPM32']."', '".($_POST['pmgPD32']+$_POST['psvPD32'])."', '".($_POST['pmgPTM32']+$_POST['psvPTM32'])."', '".($_POST['pmgPM32']+$_POST['psvPM32'])."', '".$_POST['mobilidade32']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 33, '".$_POST['sangrVD33']."', '".$_POST['sangrVTM33']."', '".$_POST['sangrVM33']."', '".$_POST['pmgVD33']."', '".$_POST['pmgVTM33']."', '".$_POST['pmgVM33']."', '".$_POST['psvVD33']."', '".$_POST['psvVTM33']."', '".$_POST['psvVM33']."', '".($_POST['pmgVD33']+$_POST['psvVD33'])."', '".($_POST['pmgVTM33']+$_POST['psvVTM33'])."', '".($_POST['pmgVM33']+$_POST['psvVM33'])."', '".$_POST['sangrPD33']."', '".$_POST['sangrPTM33']."', '".$_POST['sangrPM33']."', '".$_POST['pmgPD33']."', '".$_POST['pmgPTM33']."', '".$_POST['pmgPM33']."', '".$_POST['psvPD33']."', '".$_POST['psvPTM33']."', '".$_POST['psvPM33']."', '".($_POST['pmgPD33']+$_POST['psvPD33'])."', '".($_POST['pmgPTM33']+$_POST['psvPTM33'])."', '".($_POST['pmgPM33']+$_POST['psvPM33'])."', '".$_POST['mobilidade33']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 34, '".$_POST['sangrVD34']."', '".$_POST['sangrVTM34']."', '".$_POST['sangrVM34']."', '".$_POST['pmgVD34']."', '".$_POST['pmgVTM34']."', '".$_POST['pmgVM34']."', '".$_POST['psvVD34']."', '".$_POST['psvVTM34']."', '".$_POST['psvVM34']."', '".($_POST['pmgVD34']+$_POST['psvVD34'])."', '".($_POST['pmgVTM34']+$_POST['psvVTM34'])."', '".($_POST['pmgVM34']+$_POST['psvVM34'])."', '".$_POST['sangrPD34']."', '".$_POST['sangrPTM34']."', '".$_POST['sangrPM34']."', '".$_POST['pmgPD34']."', '".$_POST['pmgPTM34']."', '".$_POST['pmgPM34']."', '".$_POST['psvPD34']."', '".$_POST['psvPTM34']."', '".$_POST['psvPM34']."', '".($_POST['pmgPD34']+$_POST['psvPD34'])."', '".($_POST['pmgPTM34']+$_POST['psvPTM34'])."', '".($_POST['pmgPM34']+$_POST['psvPM34'])."', '".$_POST['mobilidade34']."', '".$_POST['furca34D']."', '".$_POST['furca34M']."', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 35, '".$_POST['sangrVD35']."', '".$_POST['sangrVTM35']."', '".$_POST['sangrVM35']."', '".$_POST['pmgVD35']."', '".$_POST['pmgVTM35']."', '".$_POST['pmgVM35']."', '".$_POST['psvVD35']."', '".$_POST['psvVTM35']."', '".$_POST['psvVM35']."', '".($_POST['pmgVD35']+$_POST['psvVD35'])."', '".($_POST['pmgVTM35']+$_POST['psvVTM35'])."', '".($_POST['pmgVM35']+$_POST['psvVM35'])."', '".$_POST['sangrPD35']."', '".$_POST['sangrPTM35']."', '".$_POST['sangrPM35']."', '".$_POST['pmgPD35']."', '".$_POST['pmgPTM35']."', '".$_POST['pmgPM35']."', '".$_POST['psvPD35']."', '".$_POST['psvPTM35']."', '".$_POST['psvPM35']."', '".($_POST['pmgPD35']+$_POST['psvPD35'])."', '".($_POST['pmgPTM35']+$_POST['psvPTM35'])."', '".($_POST['pmgPM35']+$_POST['psvPM35'])."', '".$_POST['mobilidade35']."', 'N/A', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 36, '".$_POST['sangrVD36']."', '".$_POST['sangrVTM36']."', '".$_POST['sangrVM36']."', '".$_POST['pmgVD36']."', '".$_POST['pmgVTM36']."', '".$_POST['pmgVM36']."', '".$_POST['psvVD36']."', '".$_POST['psvVTM36']."', '".$_POST['psvVM36']."', '".($_POST['pmgVD36']+$_POST['psvVD36'])."', '".($_POST['pmgVTM36']+$_POST['psvVTM36'])."', '".($_POST['pmgVM36']+$_POST['psvVM36'])."', '".$_POST['sangrPD36']."', '".$_POST['sangrPTM36']."', '".$_POST['sangrPM36']."', '".$_POST['pmgPD36']."', '".$_POST['pmgPTM36']."', '".$_POST['pmgPM36']."', '".$_POST['psvPD36']."', '".$_POST['psvPTM36']."', '".$_POST['psvPM36']."', '".($_POST['pmgPD36']+$_POST['psvPD36'])."', '".($_POST['pmgPTM36']+$_POST['psvPTM36'])."', '".($_POST['pmgPM36']+$_POST['psvPM36'])."', '".$_POST['mobilidade36']."', '".$_POST['furca36']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 37, '".$_POST['sangrVD37']."', '".$_POST['sangrVTM37']."', '".$_POST['sangrVM37']."', '".$_POST['pmgVD37']."', '".$_POST['pmgVTM37']."', '".$_POST['pmgVM37']."', '".$_POST['psvVD37']."', '".$_POST['psvVTM37']."', '".$_POST['psvVM37']."', '".($_POST['pmgVD37']+$_POST['psvVD37'])."', '".($_POST['pmgVTM37']+$_POST['psvVTM37'])."', '".($_POST['pmgVM37']+$_POST['psvVM37'])."', '".$_POST['sangrPD37']."', '".$_POST['sangrPTM37']."', '".$_POST['sangrPM37']."', '".$_POST['pmgPD37']."', '".$_POST['pmgPTM37']."', '".$_POST['pmgPM37']."', '".$_POST['psvPD37']."', '".$_POST['psvPTM37']."', '".$_POST['psvPM37']."', '".($_POST['pmgPD37']+$_POST['psvPD37'])."', '".($_POST['pmgPTM37']+$_POST['psvPTM37'])."', '".($_POST['pmgPM37']+$_POST['psvPM37'])."', '".$_POST['mobilidade37']."', '".$_POST['furca37']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

$sql = "INSERT INTO `tb_periograma`(`nr_idPeriograma`, `nr_cpfPaciente`, `dt_data`, `nm_disciplina`, `nr_idDupla`, `nr_cpfProfessor`, `nr_dente`, `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`, `10`, `11`, `12`, `13`, `14`, `15`, `16`, `17`, `18`, `19`, `20`, `21`, `22`, `23`, `24`, `25`, `26`, `27`, `28`, `29`, `30`, `31`, `32`)  VALUES (NULL, '".$cpf."', '".date("d/m/Y", strtotime($dia))."', '".$disciplina."', ".$dupla.", '".$professor."', 38, '".$_POST['sangrVD38']."', '".$_POST['sangrVTM38']."', '".$_POST['sangrVM38']."', '".$_POST['pmgVD38']."', '".$_POST['pmgVTM38']."', '".$_POST['pmgVM38']."', '".$_POST['psvVD38']."', '".$_POST['psvVTM38']."', '".$_POST['psvVM38']."', '".($_POST['pmgVD38']+$_POST['psvVD38'])."', '".($_POST['pmgVTM38']+$_POST['psvVTM38'])."', '".($_POST['pmgVM38']+$_POST['psvVM38'])."', '".$_POST['sangrPD38']."', '".$_POST['sangrPTM38']."', '".$_POST['sangrPM38']."', '".$_POST['pmgPD38']."', '".$_POST['pmgPTM38']."', '".$_POST['pmgPM38']."', '".$_POST['psvPD38']."', '".$_POST['psvPTM38']."', '".$_POST['psvPM38']."', '".($_POST['pmgPD38']+$_POST['psvPD38'])."', '".($_POST['pmgPTM38']+$_POST['psvPTM38'])."', '".($_POST['pmgPM38']+$_POST['psvPM38'])."', '".$_POST['mobilidade38']."', '".$_POST['furca38']."', 'N/A', 'N/R', 'N/R', 'N/R', 'N/R', 'N/R')";
$resultado = mysql_query($sql) or die(mysql_error());

header("Location: periodontia.php?cpf=".$cpf);

?>